import 'package:flutter/material.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_spacing.dart';
import '../../core/theme/app_theme.dart';
import '../../core/theme/app_typography.dart';
import '../components/button/ds_button.dart';
import '../components/card/ds_card.dart';
import '../components/snackbar/ds_snackbar.dart';
import 'component_page_wrapper.dart';

class DSSnackbarPage extends StatefulWidget {
  final ThemeController themeController;
  final VoidCallback onBackToOverview;

  const DSSnackbarPage({
    super.key,
    required this.themeController,
    required this.onBackToOverview,
  });

  @override
  State<DSSnackbarPage> createState() => _DSSnackbarPageState();
}

class _DSSnackbarPageState extends State<DSSnackbarPage> {
  DSSnackbarVariant _selectedVariant = DSSnackbarVariant.info;
  final String _titleText = 'Notification Title';
  final String _messageText = 'This is a floating toast notification message generated by DSSnackbar.';

  @override
  Widget build(BuildContext context) {
    final isDark = widget.themeController.isDarkMode;

    return ComponentPageWrapper(
      title: 'DSSnackbar Notification System',
      category: 'Design System / Feedback',
      description: 'Comprehensive investigation page for DSSnackbar. Test interactive notification toasts across success, warning, danger, and info variants.',
      themeController: widget.themeController,
      onBackToOverview: widget.onBackToOverview,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Section 1: Trigger Launcher Playground
          Text(
            '1. Interactive Toast Launcher',
            style: AppTypography.h2.copyWith(
              color: isDark ? AppColors.darkTextPrimary : AppColors.lightTextPrimary,
            ),
          ),
          AppSpacing.gapVerticalMd,
          DSCard(
            variant: DSCardVariant.elevated,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Center(
                  child: DSButton(
                    text: 'Trigger ${_selectedVariant.name.toUpperCase()} Toast',
                    variant: DSButtonVariant.primary,
                    onPressed: () {
                      DSSnackbar.show(
                        context,
                        title: _titleText,
                        message: _messageText,
                        variant: _selectedVariant,
                      );
                    },
                  ),
                ),
                AppSpacing.gapVerticalLg,
                Wrap(
                  spacing: AppSpacing.lg,
                  runSpacing: AppSpacing.md,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Toast Variant:', style: AppTypography.label),
                        AppSpacing.gapVerticalXs,
                        DropdownButton<DSSnackbarVariant>(
                          value: _selectedVariant,
                          onChanged: (val) {
                            if (val != null) setState(() => _selectedVariant = val);
                          },
                          items: DSSnackbarVariant.values.map((v) {
                            return DropdownMenuItem(
                              value: v,
                              child: Text(v.name.toUpperCase()),
                            );
                          }).toList(),
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ),
          AppSpacing.gapVerticalXl,

          // Section 2: Quick Triggers Matrix
          Text(
            '2. Quick Test Triggers',
            style: AppTypography.h2.copyWith(
              color: isDark ? AppColors.darkTextPrimary : AppColors.lightTextPrimary,
            ),
          ),
          AppSpacing.gapVerticalMd,
          DSCard(
            variant: DSCardVariant.outlined,
            child: Wrap(
              spacing: AppSpacing.md,
              runSpacing: AppSpacing.md,
              children: [
                DSButton(
                  text: 'Success Toast',
                  variant: DSButtonVariant.primary,
                  onPressed: () {
                    DSSnackbar.show(
                      context,
                      title: 'Success!',
                      message: 'Operation completed successfully.',
                      variant: DSSnackbarVariant.success,
                    );
                  },
                ),
                DSButton(
                  text: 'Warning Toast',
                  variant: DSButtonVariant.outline,
                  onPressed: () {
                    DSSnackbar.show(
                      context,
                      title: 'Warning',
                      message: 'Please review your input values.',
                      variant: DSSnackbarVariant.warning,
                    );
                  },
                ),
                DSButton(
                  text: 'Danger Toast',
                  variant: DSButtonVariant.danger,
                  onPressed: () {
                    DSSnackbar.show(
                      context,
                      title: 'Critical Failure',
                      message: 'Could not complete requested network action.',
                      variant: DSSnackbarVariant.danger,
                    );
                  },
                ),
                DSButton(
                  text: 'Info Toast',
                  variant: DSButtonVariant.secondary,
                  onPressed: () {
                    DSSnackbar.show(
                      context,
                      title: 'Information',
                      message: 'New updates are available in system settings.',
                      variant: DSSnackbarVariant.info,
                    );
                  },
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
